development:
  adapter: mysql2
  database: wifi_uff_location_development
  username: root
  password: 
test:
  adapter: mysql2
  database: wifi_uff_location_test
  username: root
  password:

production:
  database: wifi_uff_location_production
  username: root
  password: 
